### PR TITLE
Marko/add capsule migration

### PR DESCRIPTION
**Pull request by markopoloparadox**
Should I increase the spec version or not?

### CODE REVIEW

**Comment by ETeissonniere** [comment]
Looking good! Do you think we could rely on the new pallet versioning feature?

https://substrate.dev/rustdocs/v3.0.0/frame_support/traits/struct.PalletVersion.html
https://github.com/paritytech/substrate/pull/7208

**Comment by markopoloparadox** [comment]
> Looking good! Do you think we could rely on the new pallet versioning feature?
> 
> https://substrate.dev/rustdocs/v3.0.0/frame_support/traits/struct.PalletVersion.html
> [paritytech/substrate#7208](https://github.com/paritytech/substrate/pull/7208)

Maybe :), I will take a look at it.

**Comment by markopoloparadox** [comment]
@ETeissonniere
We are using the new pallet versioning feature.

**Review by ETeissonniere — APPROVED** [review]
Lgtm, love the use of pallet version 🙌🏻

**Pull request merged**
