### PR TITLE
Added missing benchmark code for the nft-burn function

### PR DESCRIPTION
**Pull request by markopoloparadox**
Added missing benchmark code for the nft-burn function.

### CODE REVIEW

**Comment by ybensacq** [comment]
@markopoloparadox  you can now generate good values for benchmark with something like : 

cargo run --release --all-features -- benchmark --chain local --raw --wasm-execution compiled --execution wasm --pallet ternoa_marketplace --extrinsic "*" --steps 50 --repeat 2 --output --weight-trait
cargo run --release --all-features -- benchmark --chain local --raw --wasm-execution compiled --execution wasm --pallet ternoa_marketplace --extrinsic "*" --steps 50 --repeat 2 --output

and replace the values you put in the previous PR.

Thank you.

**Review by ybensacq — CHANGES_REQUESTED** [review]
get the good values of benchmark

**Comment by markopoloparadox** [comment]
@ybensacq  Care to explain in more details by what you mean "and replace the values you put in the previous PR.". 

The first command that you posted I am unable to run and I am getting the following error message: 
`Found argument '--weight-traits' which wasn't expected, or isn't valid in this context`

I run the second command with some modification so it benchmarks the desired extrinsic:
`cargo run --release --all-features -- benchmark --chain local --raw --wasm-execution compiled --execution wasm --pallet ternoa_nfts --extrinsic "burn" --steps 50 --repeat 2 --output .`
It compiled successfully and it takes around 25.61 µs to execute the burn extrinsic.

As far as I can see, there are no benchmarks values recorded on my previous PR so I am not sure what exactly should I replace.

**Comment by markopoloparadox** [comment]
@ybensacq The incorrectly entered weights for the burn extrinsic should now be replaced with correct ones (generated from the benchmark).

**Comment by markopoloparadox** [comment]
@ybensacq 
@ETeissonniere 

So I looked at my weight result for the burn extrinsic and it felt out of place compared to other existing weight values. So I compared the existing ones and the ones that I am getting and it looks like I am getting around half the values that we currently use.

I am going to interpolate the result (multiply with 2) so that it looks like it was calculated by the same computer that did the current numbers. If you maybe have a better solution, please feel free to leave a comment.

Just for the sake of completeness, here is the command that I run:
`cargo run --release --all-features -- benchmark --chain local --raw --wasm-execution compiled --execution wasm --pallet ternoa_nfts --extrinsic "*" --steps 100 --repeat 50000 --output .`

And here are the results that I got:

```rust
//! Autogenerated weights for ternoa_nfts
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 3.0.0
//! DATE: 2021-04-15, STEPS: [100, ], REPEAT: 50000, LOW RANGE: [], HIGH RANGE: []
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("local"), DB CACHE: 128

// Executed Command:
// target/release/ternoa
// benchmark
// --chain
// local
// --raw
// --wasm-execution
// compiled
// --execution
// wasm
// --pallet
// ternoa_nfts
// --extrinsic
// *
// --steps
// 100
// --repeat
// 50000
// --output
// .


#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;


/// Weight functions for ternoa_nfts.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> ternoa_nfts::WeightInfo for WeightInfo<T> {
	fn create() -> Weight {
		(24_001_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	fn mutate() -> Weight {
		(25_120_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	fn seal() -> Weight {
		(25_301_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	fn transfer() -> Weight {
		(26_570_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	fn burn() -> Weight {
		(24_510_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
}
```
This are the weights that we currently use: 

```rust
impl crate::WeightInfo for () {
    fn create() -> Weight {
        (72_000_000 as Weight)
            .saturating_add(DbWeight::get().reads(1 as Weight))
            .saturating_add(DbWeight::get().writes(2 as Weight))
    }
    fn mutate() -> Weight {
        (50_000_000 as Weight)
            .saturating_add(DbWeight::get().reads(1 as Weight))
            .saturating_add(DbWeight::get().writes(1 as Weight))
    }
    fn seal() -> Weight {
        (46_000_000 as Weight)
            .saturating_add(DbWeight::get().reads(1 as Weight))
            .saturating_add(DbWeight::get().writes(1 as Weight))
    }
    fn transfer() -> Weight {
        (47_000_000 as Weight)
            .saturating_add(DbWeight::get().reads(1 as Weight))
            .saturating_add(DbWeight::get().writes(1 as Weight))
    }
    fn burn() -> Weight {
        (25_380_000 as Weight)
            .saturating_add(DbWeight::get().reads(1 as Weight))
            .saturating_add(DbWeight::get().writes(1 as Weight))
    }
}
```

**Comment by ETeissonniere** [comment]
@markopoloparadox for now we are running as a chaos net so this ain't the most sensitive thing (as in we can play around with the settings) - how about we keep it simple and regenerate all the weights for this pallet from your laptop? We will just change it next time or when we compute the production weights

**Comment by markopoloparadox** [comment]
@ETeissonniere That sounds like a reasonable option. I will change them right now.

**Pull request merged**
