### PR TITLE
Nfts are not anymore listed for sale once bought

### PR DESCRIPTION
**Pull request by markopoloparadox**
Should fix the bug where you could buy an nft which was then sold but it was still marked for sale.

### CODE REVIEW

**Review by ETeissonniere — APPROVED** [review]

**Review by ETeissonniere — CHANGES_REQUESTED** [review]
seems like one of the tests is failing

**Comment by markopoloparadox** [comment]
@ETeissonniere Yeah I saw that and fixed the broken tests 4 mins ago. I also updated the weights.

**Review by ETeissonniere — APPROVED** [review]
lgtm

**Review by ETeissonniere — CHANGES_REQUESTED** [review]
@markopoloparadox @ybensacq just mentioned he was looking at updating the chain with this changes. Can you make sure to bump the `spec_version` value in the runtime folder? Thanks

**Comment by markopoloparadox** [comment]
@ETeissonniere Sure. Will do it right now!

**Comment by markopoloparadox** [comment]
@ETeissonniere It's done. For some reason, I always forget to update the runtime spec/impl version 🙃

**Review by ETeissonniere — APPROVED** [review]
no problems! maybe we could add a test to enforce this. Anyways, 100% looks good to me now - feel free to merge

**Pull request merged**
